# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="true"

install:
  - source tests/travis_install.sh
  - pip install .
# before_script:
#   - git config --global user.email "you@example.com"
#   - git config --global user.name "Your Name"
script:
  - pip install .[testing]
  - pytest
#   - |
#     if [[ "$COVERAGE" == "true" ]]; then
#       pre-commit install
#       pre-commit run --all-files
#     fi

# notification settings
notifications:
    email:
        recipients:
            - consistentbayes@gmail.com
        on_success: change
        on_failure: always

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then codecov ; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
