name: builds

on:
  push:
    branches: [ main ]
    paths:
      - "src/**.py"
      - "tests/**.py"
      - "setup.py"
      - "setup.cfg"
      - ".github/workflows/build.yml"
  pull_request:
    branches-ignore: '**docker**'
    paths:
      - "src/**.py"
      - "tests/**.py"
      - "setup.py"
      - "setup.cfg"
      - ".github/workflows/build.yml"
  schedule:
      - cron: "0 0 1 * *"

jobs:
  build:
    name: Test build process
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade wheel setuptools setuptools_scm

      - name: Inspect version info
        run: | 
          python setup.py --version
          git describe --dirty --tags --long --match "*[0-9]*"

      - name: Test pip install to site-packages
        run: |
          pip install .
          pip uninstall -y mud

      - name: Test pip install local
        run: |
          pip install -e .
          pip uninstall -y mud
 
      - name: Test build
        run: |
          python setup.py sdist bdist_wheel
          pip uninstall -y mud


  style:
    name: Enforce style
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: linting
        run: |
          flake8 .
          black --check .

      - name: import sorts
        run: isort -c .

      - name: type checks
        run: |
          mypy src/mud/ tests/
