# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #release:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    strategy:
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python3 -m pip install --upgrade setuptools wheel
          python3 -m pip install --upgrade twine pytest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest-cov pytest-virtualenv coverage coveralls flake8 pre-commit
          pip install .
          #pip install -r requirements-dev.txt
          # install black if available (Python 3.6 and above)
          pip install black || true

      - name: Run tests
        run: pytest

      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish release ${{ github.ref }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
